spring:
  application:
    name: expense-api
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/expense_db}
    username: ${DB_USERNAME:expense_user}
    password: ${DB_PASSWORD:expense_password}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8090}