{{- range $service := list .Values.services.orderApi .Values.services.orderProcessor .Values.services.notification }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  labels:
    app.kubernetes.io/name: {{ $service.name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $service.name }}
        app.kubernetes.io/part-of: order-platform
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: {{ $service.name }}
          image: "{{ $.Values.image.registry }}/{{ $service.name }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          ports: [{ name: http, containerPort: {{ $service.containerPort }} }]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: { drop: [ALL] }
          resources: {{- toYaml $.Values.resources | nindent 12 }}
          readinessProbe:
            httpGet: { path: /actuator/health/readiness, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health/liveness, port: http }
            initialDelaySeconds: 30
            periodSeconds: 20
---
{{- end }}